class EEGPlotter:
    def plot_raw(self, raw: mne.io.Raw) -> None: ...
    def plot_epochs(self, epochs: mne.Epochs) -> None: ...
    def plot_topomap(self, evoked: mne.Evoked, times: list) -> None: ...
