class TEPPlotter:
    def plot_butterfly(self, evoked: mne.Evoked) -> None: ...
    def plot_component_latencies(self, components: dict) -> None: ...
    def plot_tfr(self, tfr: mne.time_frequency.AverageTFR) -> None: ...
