class ArtifactRemover:
    def remove_tms_pulse(self, raw: mne.io.Raw, config: TMSConfig) -> mne.io.Raw: ...
    def run_ica(self, raw: mne.io.Raw) -> mne.preprocessing.ICA: ...
    def apply_ica(self, raw: mne.io.Raw, ica: mne.preprocessing.ICA) -> mne.io.Raw: ...
